'use client';

import { Starfield } from './Starfield';

/**
 * The site's background, mounted once in the root layout.
 *
 * Fixed rather than scrolling: a scrolling background would need to be as
 * tall as the document, and every section would meet the next at a visible
 * seam. Fixed, with the stars drifting at a fraction of scroll speed, gives
 * one continuous sky.
 *
 * ── On the colour ──────────────────────────────────────────────────────
 *
 * The reference is a saturated violet nebula. Two constraints shaped how
 * far that could be taken:
 *
 * 1. §8 assigns violet to AI/ML, cyan to Web, teal to DSA. A uniformly
 *    violet sky would make the colour that *means* "AI" identical to the
 *    colour that means "background", and the palette would stop carrying
 *    information. So violet leads, but cyan and magenta carry real weight
 *    and no single hue covers the whole field.
 *
 * 2. §61 needs contrast. Opacities here were set against measured contrast
 *    ratios, not by eye: at the densest overlap the background reaches
 *    roughly #392969, where body text scores 11.1 and muted text 5.0
 *    against a 4.5 threshold. The one colour that does *not* clear it
 *    there is `--color-ink-faint`, which is why small captions live on
 *    `.plate` and `.panel` surfaces rather than directly on the sky.
 */
export function SpaceBackground() {
  return (
    <div
      aria-hidden
      className="space-bg pointer-events-none fixed inset-0 -z-10 overflow-hidden"
    >
      {/* Base wash. Light gathers low, so the page has a direction. */}
      <div className="absolute inset-0 bg-[radial-gradient(150%_110%_at_50%_105%,#140f2e_0%,#0a0a1c_45%,#05070e_100%)]" />

      {/*
        Nebula field.

        Watercolour depth comes from many soft blobs at different sizes and
        blurs rather than from one big gradient — a single blob reads as a
        vignette, several overlapping read as cloud. Sizes are in vw so the
        composition holds its proportions at any viewport.
      */}
      <div className="absolute -right-[8%] -top-[6%] h-[58vw] w-[58vw] rounded-full bg-[radial-gradient(circle,rgba(139,92,246,0.30)_0%,rgba(139,92,246,0.12)_38%,transparent_68%)] blur-[80px]" />

      <div className="absolute right-[18%] top-[12%] h-[30vw] w-[30vw] rounded-full bg-[radial-gradient(circle,rgba(196,132,252,0.22)_0%,transparent_62%)] blur-[60px]" />

      <div className="absolute -left-[14%] top-[28%] h-[52vw] w-[52vw] rounded-full bg-[radial-gradient(circle,rgba(34,211,238,0.16)_0%,rgba(59,130,246,0.10)_42%,transparent_70%)] blur-[90px]" />

      <div className="absolute left-[22%] top-[58%] h-[40vw] w-[40vw] rounded-full bg-[radial-gradient(circle,rgba(168,85,247,0.20)_0%,transparent_65%)] blur-[70px]" />

      <div className="absolute -right-[10%] top-[62%] h-[44vw] w-[44vw] rounded-full bg-[radial-gradient(circle,rgba(99,102,241,0.18)_0%,transparent_66%)] blur-[85px]" />

      {/* A single warm note. Without it the field reads as one hue tinted
          lighter and darker; a small opposing temperature is what makes the
          violets look like violets. */}
      <div className="absolute left-[52%] top-[40%] h-[22vw] w-[22vw] rounded-full bg-[radial-gradient(circle,rgba(244,164,120,0.09)_0%,transparent_60%)] blur-[70px]" />

      <Starfield density={340} brightness={0.8} scrollFactor={0.1} />

      {/*
        Grain.

        Large flat gradients band visibly on 8-bit displays — you see rings
        where the shader steps between values. A little noise on top breaks
        the steps up and is also what gives the reference its painted
        rather than rendered quality. Generated by the browser's own
        turbulence filter, so it costs no image request.
      */}
      <div
        className="absolute inset-0 opacity-[0.16] mix-blend-overlay"
        style={{
          backgroundImage:
            "url(\"data:image/svg+xml,%3Csvg xmlns='http://www.w3.org/2000/svg' width='220' height='220'%3E%3Cfilter id='n'%3E%3CfeTurbulence type='fractalNoise' baseFrequency='0.85' numOctaves='3' stitchTiles='stitch'/%3E%3C/filter%3E%3Crect width='220' height='220' filter='url(%23n)' opacity='0.5'/%3E%3C/svg%3E\")",
        }}
      />

      {/* Vignette. Pulls the eye to the centre column where content sits,
          and darkens the extreme edges where the nebulae are densest. */}
      <div className="absolute inset-0 bg-[radial-gradient(120%_90%_at_50%_45%,transparent_35%,rgba(5,7,14,0.55)_100%)]" />
    </div>
  );
}
