import type { Project } from '@/types/project';

/**
 * DEVELOPMENT FIXTURES — NOT KHUSH'S PROJECTS.
 *
 * These are not seed data in the usual sense. They are not scraped
 * versions of real repositories, and they must never be published.
 *
 * Why they exist: chunks 06–10 build the project grid, detail page,
 * architecture view and data-layer view. Those need something to render
 * against, and they need to be exercised against every state the analyser
 * can produce — not just the happy one. If the only test data were three
 * clean full-stack apps, the "no database detected" and "unknown"
 * branches would be written blind and break the first time a real
 * repository hit them.
 *
 * So the set is chosen to cover all six `DataLayer` kinds and a spread of
 * categories and confidence levels. Every record carries `isFixture: true`
 * and is filtered out of any production build by `dataSource`.
 *
 * Real project records arrive at chunk 17, generated by the analyser from
 * the actual repositories. Hand-writing them here would be a manual
 * project card with extra steps — exactly what §4 forbids.
 */

export const fixtureProjects: Project[] = [
  {
    id: 'fx-1',
    slug: 'fixture-sql-fullstack',
    isFixture: true,
    status: 'ready',
    name: 'Fixture — relational full stack',
    description:
      'Exercises the SQL data-layer view: tables, primary and foreign keys, and one-to-many relationships.',
    category: 'web',
    categoryConfidence: 0.92,
    domain: 'web',
    repository: {
      id: 'fx-repo-1',
      owner: 'fixture',
      name: 'relational-app',
      url: 'https://github.com/fixture/relational-app',
      visibility: 'public',
      defaultBranch: 'main',
      isFork: false,
      parentUrl: null,
      lastAnalyzedAt: null,
      latestCommitSha: null,
    },
    technologies: [
      {
        id: 'react',
        name: 'React',
        category: 'frontend',
        level: 'confirmed',
        confidence: 1,
        evidence: [{ file: 'package.json', note: 'dependency' }],
      },
      {
        id: 'postgresql',
        name: 'PostgreSQL',
        category: 'database',
        level: 'confirmed',
        confidence: 1,
        evidence: [
          { file: 'prisma/schema.prisma', note: 'provider = "postgresql"' },
        ],
      },
      {
        id: 'express',
        name: 'Express',
        category: 'backend',
        level: 'confirmed',
        confidence: 1,
        evidence: [{ file: 'package.json' }],
      },
    ],
    features: [
      'Session-based authentication',
      'Role-scoped project access',
    ],
    architecture: {
      nodes: [
        {
          id: 'client',
          label: 'Browser',
          type: 'client',
          description: 'Where the visitor interacts with the application.',
          level: 'confirmed',
          confidence: 1,
          evidence: [{ file: 'src/main.tsx' }],
        },
        {
          id: 'api',
          label: 'Express API',
          type: 'api',
          description: 'REST layer handling authentication and CRUD.',
          level: 'confirmed',
          confidence: 1,
          evidence: [{ file: 'server/routes/index.ts' }],
        },
        {
          id: 'db',
          label: 'PostgreSQL',
          type: 'datastore',
          description: 'Persistent relational store, accessed through Prisma.',
          level: 'confirmed',
          confidence: 1,
          evidence: [{ file: 'prisma/schema.prisma' }],
        },
      ],
      edges: [
        { id: 'e1', from: 'client', to: 'api', label: 'REST' },
        { id: 'e2', from: 'api', to: 'db', label: 'Prisma' },
      ],
    },
    dataLayer: {
      kind: 'sql',
      engine: 'PostgreSQL',
      tables: [
        {
          name: 'users',
          columns: [
            { name: 'id', type: 'uuid', primaryKey: true },
            { name: 'email', type: 'text' },
            { name: 'created_at', type: 'timestamptz' },
          ],
        },
        {
          name: 'projects',
          columns: [
            { name: 'id', type: 'uuid', primaryKey: true },
            { name: 'user_id', type: 'uuid', foreignKey: 'users' },
            { name: 'name', type: 'text' },
          ],
        },
      ],
      relationships: [{ from: 'users', to: 'projects', cardinality: '1:N' }],
      claim: {
        level: 'confirmed',
        confidence: 1,
        evidence: [{ file: 'prisma/schema.prisma' }],
      },
    },
    unknowns: [],
    liveUrl: null,
    previewImageUrl: null,
  },

  {
    id: 'fx-2',
    slug: 'fixture-vector-rag',
    isFixture: true,
    status: 'ready',
    name: 'Fixture — retrieval pipeline',
    description:
      'Exercises the vector data-layer view, which must render as a flow rather than a fake table schema.',
    category: 'ai',
    categoryConfidence: 0.88,
    domain: 'ai',
    repository: {
      id: 'fx-repo-2',
      owner: 'fixture',
      name: 'retrieval-service',
      url: 'https://github.com/fixture/retrieval-service',
      visibility: 'public',
      defaultBranch: 'main',
      isFork: false,
      parentUrl: null,
      lastAnalyzedAt: null,
      latestCommitSha: null,
    },
    technologies: [
      {
        id: 'python',
        name: 'Python',
        category: 'language',
        level: 'confirmed',
        confidence: 1,
        evidence: [{ file: 'pyproject.toml' }],
      },
      {
        id: 'langchain',
        name: 'LangChain',
        category: 'ai',
        level: 'confirmed',
        confidence: 1,
        evidence: [{ file: 'requirements.txt' }],
      },
      {
        id: 'fastapi',
        name: 'FastAPI',
        category: 'backend',
        level: 'inferred',
        confidence: 0.6,
        evidence: [{ file: 'app/main.py', note: 'import pattern only' }],
      },
    ],
    features: ['Document chunking', 'Similarity search over embeddings'],
    architecture: null,
    dataLayer: {
      kind: 'vector',
      store: 'Chroma',
      pipeline: [
        { id: 'docs', label: 'Documents' },
        { id: 'chunk', label: 'Chunking' },
        { id: 'embed', label: 'Embeddings' },
        { id: 'store', label: 'Vector store' },
        { id: 'search', label: 'Similarity search' },
        { id: 'llm', label: 'LLM' },
      ],
      claim: {
        level: 'confirmed',
        confidence: 0.9,
        evidence: [{ file: 'app/rag/store.py' }],
      },
    },
    unknowns: ['Deployment target could not be determined.'],
    liveUrl: null,
    previewImageUrl: null,
  },

  {
    id: 'fx-3',
    slug: 'fixture-no-database',
    isFixture: true,
    status: 'ready',
    name: 'Fixture — no persistent store',
    description:
      'Exercises the "no database detected" state. This is the state most likely to be got wrong, because the temptation is to render an empty table instead of nothing.',
    category: 'dsa',
    categoryConfidence: 0.95,
    domain: 'dsa',
    repository: {
      id: 'fx-repo-3',
      owner: 'fixture',
      name: 'algorithms',
      url: 'https://github.com/fixture/algorithms',
      visibility: 'public',
      defaultBranch: 'main',
      isFork: false,
      parentUrl: null,
      lastAnalyzedAt: null,
      latestCommitSha: null,
    },
    technologies: [
      {
        id: 'cpp',
        name: 'C++',
        category: 'language',
        level: 'confirmed',
        confidence: 1,
        evidence: [{ file: 'CMakeLists.txt' }],
      },
    ],
    features: [],
    architecture: null,
    dataLayer: {
      kind: 'none',
      claim: {
        level: 'confirmed',
        confidence: 0.95,
        evidence: [
          { file: 'CMakeLists.txt', note: 'no database dependency present' },
        ],
      },
    },
    unknowns: [],
    liveUrl: null,
    previewImageUrl: null,
  },

  {
    id: 'fx-4',
    slug: 'fixture-unknown-layer',
    isFixture: true,
    status: 'ready',
    name: 'Fixture — insufficient evidence',
    description:
      'Exercises the "unknown" state, which is deliberately different from "none". A thin repository with no README lands here.',
    category: 'other',
    categoryConfidence: 0.3,
    domain: 'other',
    repository: {
      id: 'fx-repo-4',
      owner: 'fixture',
      name: 'sparse-repo',
      url: 'https://github.com/fixture/sparse-repo',
      visibility: 'public',
      defaultBranch: 'main',
      isFork: false,
      parentUrl: null,
      lastAnalyzedAt: null,
      latestCommitSha: null,
    },
    technologies: [],
    features: [],
    architecture: null,
    dataLayer: { kind: 'unknown' },
    unknowns: [
      'No README was found.',
      'No dependency manifest was found.',
      'Project category is a low-confidence guess.',
    ],
    liveUrl: null,
    previewImageUrl: null,
  },

  {
    id: 'fx-5',
    slug: 'fixture-document-store',
    isFixture: true,
    status: 'ready',
    name: 'Fixture — document store',
    description:
      'Exercises the MongoDB view. Collections and references, never rendered as relational tables (spec §30).',
    category: 'backend',
    categoryConfidence: 0.85,
    domain: 'web',
    repository: {
      id: 'fx-repo-5',
      owner: 'fixture',
      name: 'document-api',
      url: 'https://github.com/fixture/document-api',
      visibility: 'public',
      defaultBranch: 'main',
      isFork: false,
      parentUrl: null,
      lastAnalyzedAt: null,
      latestCommitSha: null,
    },
    technologies: [
      {
        id: 'mongodb',
        name: 'MongoDB',
        category: 'database',
        level: 'confirmed',
        confidence: 1,
        evidence: [{ file: 'src/models/user.model.js', note: 'mongoose schema' }],
      },
      {
        id: 'node',
        name: 'Node.js',
        category: 'backend',
        level: 'confirmed',
        confidence: 1,
        evidence: [{ file: 'package.json' }],
      },
    ],
    features: ['Document-based persistence'],
    architecture: null,
    dataLayer: {
      kind: 'document',
      engine: 'MongoDB',
      collections: [
        {
          name: 'users',
          fields: [
            { name: '_id', type: 'ObjectId' },
            { name: 'email', type: 'String' },
          ],
        },
        {
          name: 'tasks',
          fields: [
            { name: '_id', type: 'ObjectId' },
            { name: 'userId', type: 'ObjectId', references: 'users' },
            { name: 'title', type: 'String' },
          ],
        },
      ],
      claim: {
        level: 'confirmed',
        confidence: 0.95,
        evidence: [{ file: 'src/models/task.model.js' }],
      },
    },
    unknowns: [],
    liveUrl: null,
    previewImageUrl: null,
  },

  {
    id: 'fx-6',
    slug: 'fixture-keyvalue',
    isFixture: true,
    status: 'hidden',
    name: 'Fixture — key-value roles',
    description:
      'Exercises the Redis view and, because its status is hidden, also the owner-only filtering path.',
    category: 'devtool',
    categoryConfidence: 0.7,
    domain: 'other',
    repository: {
      id: 'fx-repo-6',
      owner: 'fixture',
      name: 'queue-worker',
      url: 'https://github.com/fixture/queue-worker',
      visibility: 'public',
      defaultBranch: 'main',
      isFork: false,
      parentUrl: null,
      lastAnalyzedAt: null,
      latestCommitSha: null,
    },
    technologies: [
      {
        id: 'redis',
        name: 'Redis',
        category: 'database',
        level: 'confirmed',
        confidence: 1,
        evidence: [{ file: 'docker-compose.yml' }],
      },
    ],
    features: [],
    architecture: null,
    dataLayer: {
      kind: 'keyvalue',
      engine: 'Redis',
      // Only roles with evidence. No 'session' here — nothing supports it.
      roles: ['cache', 'queue'],
      claim: {
        level: 'confirmed',
        confidence: 0.9,
        evidence: [
          { file: 'src/queue.ts', note: 'BullMQ queue' },
          { file: 'src/cache.ts' },
        ],
      },
    },
    unknowns: [],
    liveUrl: null,
    previewImageUrl: null,
  },
];
